//! Rust code generator — emits a `SvelteComponent` implementation from an IR tree.
//!
//! The generated code uses `svelte_ratatui_compiler::ir` types and
//! `svelte_ratatui_compiler::mapping::render_ir` at runtime, keeping the
//! generated source minimal: it constructs the IR tree and delegates
//! rendering to the existing mapping module.

use crate::ir::IrNode;

/// Generate a Rust source file implementing `SvelteComponent` for the given
/// component name and IR tree.
pub fn generate(component_name: &str, root: &IrNode) -> String {
    let mut out = String::with_capacity(2048);

    // Header
    out.push_str("//! Auto-generated by svelte-ratatui compiler. Do not edit.\n\n");
    out.push_str("use std::collections::HashMap;\n");
    out.push_str("use crossterm::event::Event;\n");
    out.push_str("use ratatui::Frame;\n");
    out.push_str("use ratatui::layout::Rect;\n");
    out.push_str("use svelte_ratatui_compiler::ir::{IrElement, IrNode};\n");
    out.push_str("use svelte_ratatui_compiler::mapping::render_ir;\n");
    out.push_str("use svelte_ratatui_runtime::SvelteComponent;\n\n");

    // Struct
    out.push_str(&format!("pub struct {component_name};\n\n"));

    // SvelteComponent impl
    out.push_str(&format!("impl SvelteComponent for {component_name} {{\n"));

    // render method
    out.push_str("    fn render(&self, frame: &mut Frame, area: Rect) {\n");
    out.push_str("        let root = ");
    emit_ir_node(&mut out, root, 2);
    out.push_str(";\n");
    out.push_str("        render_ir(frame, area, &root);\n");
    out.push_str("    }\n\n");

    // handle_event method
    out.push_str("    fn handle_event(&mut self, _event: Event) -> bool {\n");
    out.push_str("        false\n");
    out.push_str("    }\n");

    out.push_str("}\n");

    out
}

/// Emit Rust code that constructs an IrNode value.
fn emit_ir_node(out: &mut String, node: &IrNode, indent: usize) {
    let pad = "    ".repeat(indent);
    match node {
        IrNode::Text(s) => {
            out.push_str(&format!("IrNode::text({:?})", s));
        }
        IrNode::Element(el) => {
            out.push_str("IrNode::Element(IrElement {\n");

            // tag
            out.push_str(&format!("{pad}    tag: {:?}.into(),\n", el.tag));

            // attrs
            if el.attrs.is_empty() {
                out.push_str(&format!("{pad}    attrs: HashMap::new(),\n"));
            } else {
                out.push_str(&format!("{pad}    attrs: HashMap::from([\n"));
                for (k, v) in &el.attrs {
                    out.push_str(&format!(
                        "{pad}        ({:?}.into(), {:?}.into()),\n",
                        k, v
                    ));
                }
                out.push_str(&format!("{pad}    ]),\n"));
            }

            // styles
            if el.styles.is_empty() {
                out.push_str(&format!("{pad}    styles: HashMap::new(),\n"));
            } else {
                out.push_str(&format!("{pad}    styles: HashMap::from([\n"));
                for (k, v) in &el.styles {
                    out.push_str(&format!(
                        "{pad}        ({:?}.into(), {:?}.into()),\n",
                        k, v
                    ));
                }
                out.push_str(&format!("{pad}    ]),\n"));
            }

            // children
            if el.children.is_empty() {
                out.push_str(&format!("{pad}    children: Vec::new(),\n"));
            } else {
                out.push_str(&format!("{pad}    children: vec![\n"));
                for child in &el.children {
                    out.push_str(&format!("{pad}        "));
                    emit_ir_node(out, child, indent + 2);
                    out.push_str(",\n");
                }
                out.push_str(&format!("{pad}    ],\n"));
            }

            out.push_str(&format!("{pad}}})"));
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ir::IrNode;
    use std::collections::HashMap;

    #[test]
    fn generate_simple_text() {
        let root = IrNode::text("Hello");
        let code = generate("Hello", &root);
        assert!(code.contains("pub struct Hello;"));
        assert!(code.contains("IrNode::text(\"Hello\")"));
        assert!(code.contains("render_ir(frame, area, &root)"));
    }

    #[test]
    fn generate_element_with_children() {
        let root = IrNode::Element(IrElement {
            tag: "div".into(),
            attrs: HashMap::new(),
            styles: HashMap::new(),
            children: vec![
                IrNode::Element(IrElement {
                    tag: "h1".into(),
                    attrs: HashMap::new(),
                    styles: HashMap::new(),
                    children: vec![IrNode::text("Title")],
                }),
                IrNode::Element(IrElement {
                    tag: "p".into(),
                    attrs: HashMap::new(),
                    styles: HashMap::new(),
                    children: vec![IrNode::text("Body text")],
                }),
            ],
        });
        let code = generate("MyComponent", &root);
        assert!(code.contains("pub struct MyComponent;"));
        assert!(code.contains("\"div\""));
        assert!(code.contains("\"h1\""));
        assert!(code.contains("\"Title\""));
        assert!(code.contains("\"Body text\""));
    }

    #[test]
    fn generate_element_with_styles() {
        let root = IrNode::Element(IrElement {
            tag: "p".into(),
            attrs: HashMap::new(),
            styles: HashMap::from([("color".to_string(), "red".to_string())]),
            children: vec![IrNode::text("Red")],
        });
        let code = generate("Styled", &root);
        assert!(code.contains("\"color\""));
        assert!(code.contains("\"red\""));
    }
}
