[package]
name = "svelte-ratatui-cli"
description = "CLI tool for compiling Svelte components to ratatui"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "svelte-ratatui"
path = "src/main.rs"

[dependencies]
svelte-ratatui-compiler = { path = "../svelte-ratatui-compiler" }
clap = { version = "4", features = ["derive"] }
notify = "6.1"
walkdir = "2"

[dev-dependencies]
tempfile = "3"
